const { prisma } = require("../config/db");

const getSummary = async (vendorId, from, to) => {
  const now = new Date();
  
  // Set date ranges
  const todayStart = new Date(now.setHours(0, 0, 0, 0));
  const todayEnd = new Date(now.setHours(23, 59, 59, 999));
  
  const fromDate = from ? new Date(from) : new Date(new Date().setDate(now.getDate() - 7));
  const toDate = to ? new Date(to) : new Date();

  // 1. Counts for today
  const todayOrdersCount = await prisma.order.count({
    where: {
      vendorId,
      createdAt: { gte: todayStart, lte: todayEnd },
    },
  });

  const lateOrdersCount = await prisma.order.count({
    where: {
      vendorId,
      status: "OVERDUE",
    },
  });

  const pickupWorkflowsCount = await prisma.pickupReturnWorkflow.count({
    where: {
      order: { vendorId },
      workflowType: "PICKUP",
      scheduledDate: { gte: todayStart, lte: todayEnd },
    },
  });

  const returnWorkflowsCount = await prisma.pickupReturnWorkflow.count({
    where: {
      order: { vendorId },
      workflowType: "RETURN",
      scheduledDate: { gte: todayStart, lte: todayEnd },
    },
  });

  // 2. Sales / Revenue metrics (last 7 days vs prior 7 days)
  const last7DaysStart = new Date();
  last7DaysStart.setDate(last7DaysStart.getDate() - 7);
  
  const prior7DaysStart = new Date();
  prior7DaysStart.setDate(prior7DaysStart.getDate() - 14);
  const prior7DaysEnd = new Date(last7DaysStart);

  // Sales last 7 days
  const salesLast7DaysRes = await prisma.order.aggregate({
    _sum: { totalAmount: true },
    where: {
      vendorId,
      createdAt: { gte: last7DaysStart },
    },
  });
  const salesLast7Days = Number(salesLast7DaysRes._sum.totalAmount || 0);

  // Sales prior 7 days
  const salesPrior7DaysRes = await prisma.order.aggregate({
    _sum: { totalAmount: true },
    where: {
      vendorId,
      createdAt: { gte: prior7DaysStart, lt: prior7DaysEnd },
    },
  });
  const salesPrior7Days = Number(salesPrior7DaysRes._sum.totalAmount || 0);
  
  // Calculate percentage change
  let salesChangePercent = 0;
  if (salesPrior7Days > 0) {
    salesChangePercent = ((salesLast7Days - salesPrior7Days) / salesPrior7Days) * 100;
  }

  // 3. Late fees collected (last 7 days vs prior 7 days)
  const lateFeesLast7DaysRes = await prisma.orderItem.aggregate({
    _sum: { amount: true },
    where: {
      order: { vendorId },
      isAutoGenerated: true,
      order: { createdAt: { gte: last7DaysStart } },
    },
  });
  const lateFeesCollected = Number(lateFeesLast7DaysRes._sum.amount || 0);

  const lateFeesPrior7DaysRes = await prisma.orderItem.aggregate({
    _sum: { amount: true },
    where: {
      order: { vendorId },
      isAutoGenerated: true,
      order: { createdAt: { gte: prior7DaysStart, lt: prior7DaysEnd } },
    },
  });
  const lateFeesPrior = Number(lateFeesPrior7DaysRes._sum.amount || 0);

  let lateFeesChangePercent = 0;
  if (lateFeesPrior > 0) {
    lateFeesChangePercent = ((lateFeesCollected - lateFeesPrior) / lateFeesPrior) * 100;
  }

  // 4. Deposits held
  const depositsRes = await prisma.securityDepositInvoice.aggregate({
    _sum: { depositAmount: true },
    where: {
      order: { vendorId },
      depositStatus: "HELD",
    },
  });
  const depositHeld = Number(depositsRes._sum.depositAmount || 0);

  // For change percent, compare total held deposits created in last 7 days vs prior 7 days
  const depositsLast7Res = await prisma.securityDepositInvoice.aggregate({
    _sum: { depositAmount: true },
    where: {
      order: { vendorId },
      depositStatus: "HELD",
      createdAt: { gte: last7DaysStart },
    },
  });
  const depositsLast7 = Number(depositsLast7Res._sum.depositAmount || 0);

  const depositsPrior7Res = await prisma.securityDepositInvoice.aggregate({
    _sum: { depositAmount: true },
    where: {
      order: { vendorId },
      depositStatus: "HELD",
      createdAt: { gte: prior7DaysStart, lt: prior7DaysEnd },
    },
  });
  const depositsPrior7 = Number(depositsPrior7Res._sum.depositAmount || 0);

  let depositChangePercent = 0;
  if (depositsPrior7 > 0) {
    depositChangePercent = ((depositsLast7 - depositsPrior7) / depositsPrior7) * 100;
  }

  // 5. Rental lifecycle counts
  const activeRentals = await prisma.order.count({
    where: {
      vendorId,
      status: { in: ["RENTED", "OVERDUE"] },
    },
  });

  const rentalsDueToday = await prisma.order.count({
    where: {
      vendorId,
      scheduledReturnDate: { gte: todayStart, lte: todayEnd },
    },
  });

  const overdueRentals = await prisma.order.count({
    where: {
      vendorId,
      status: "OVERDUE",
    },
  });

  return {
    today: todayOrdersCount,
    late: lateOrdersCount,
    pickup: pickupWorkflowsCount,
    return: returnWorkflowsCount,
    salesLast7Days,
    salesChangePercent: parseFloat(salesChangePercent.toFixed(1)),
    lateFeesCollected,
    lateFeesChangePercent: parseFloat(lateFeesChangePercent.toFixed(1)),
    depositHeld,
    depositChangePercent: parseFloat(depositChangePercent.toFixed(1)),
    activeRentals,
    rentalsDueToday,
    overdueRentals,
  };
};

const getActiveRentals = async (vendorId) => {
  const orders = await prisma.order.findMany({
    where: {
      vendorId,
      status: "RENTED",
    },
    include: {
      client: true,
      items: { include: { product: true } },
    },
    orderBy: { scheduledReturnDate: "asc" },
  });

  return {
    orders,
    total: orders.length,
  };
};

const getOverdueRentals = async (vendorId) => {
  const orders = await prisma.order.findMany({
    where: {
      vendorId,
      status: "OVERDUE",
    },
    include: {
      client: true,
      items: { include: { product: true } },
    },
    orderBy: { scheduledReturnDate: "asc" },
  });

  return {
    orders,
    total: orders.length,
  };
};

const getRevenueSeries = async (vendorId, from, to, groupBy = "day") => {
  const fromDate = from ? new Date(from) : new Date(new Date().setDate(new Date().getDate() - 30));
  const toDate = to ? new Date(to) : new Date();

  // Get orders in date range
  const orders = await prisma.order.findMany({
    where: {
      vendorId,
      createdAt: { gte: fromDate, lte: toDate },
      status: { not: "CANCELLED" },
    },
    select: {
      createdAt: true,
      totalAmount: true,
    },
    orderBy: { createdAt: "asc" },
  });

  // Grouping logic
  const groups = {};

  orders.forEach(order => {
    let key = "";
    const date = new Date(order.createdAt);
    
    if (groupBy === "day") {
      key = date.toISOString().split("T")[0]; // YYYY-MM-DD
    } else if (groupBy === "week") {
      // Calculate start of week (Sunday)
      const day = date.getDay();
      const diff = date.getDate() - day;
      const startOfWeek = new Date(date.setDate(diff));
      key = startOfWeek.toISOString().split("T")[0];
    } else if (groupBy === "month") {
      key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; // YYYY-MM
    }

    groups[key] = (groups[key] || 0) + Number(order.totalAmount);
  });

  const series = Object.keys(groups).map(key => ({
    label: key,
    value: groups[key],
  }));

  return series;
};

module.exports = {
  getSummary,
  getActiveRentals,
  getOverdueRentals,
  getRevenueSeries,
};
