const repo = require('../repositories/invoice.repository');
const ApiError = require('../utils/apiError');

exports.createInvoice = async (data) => {
  const { lines, ...invoiceData } = data;
  
  // Generate invoice number if not provided
  if (!invoiceData.invoiceNumber) {
    invoiceData.invoiceNumber = `INV-${Date.now()}`;
  }

  return await repo.create({
    ...invoiceData,
    lines: {
      create: lines.map(line => ({
        productId: line.productId,
        quantity: line.quantity,
        unit: line.unit,
        unitPrice: line.unitPrice,
        amount: line.amount,
        isAutoGenerated: line.isAutoGenerated
      }))
    }
  });
};

exports.getInvoices = async () => {
  return await repo.findMany({});
};

exports.getInvoiceById = async (id) => {
  const invoice = await repo.findById(id);
  if (!invoice) throw new ApiError(404, 'Invoice not found');
  return invoice;
};

exports.postInvoice = async (id) => {
  const invoice = await repo.findById(id);
  if (!invoice) throw new ApiError(404, 'Invoice not found');
  
  if (invoice.state === 'POSTED') {
    throw new ApiError(400, 'Invoice is already posted');
  }

  return await repo.updateState(id, 'POSTED', new Date());
};
