const repo = require('../repositories/invoice.repository');
const ApiError = require('../utils/apiError');
const { prisma } = require('../config/db');

exports.createInvoice = async (data) => {
  const { lines, ...invoiceData } = data;
  
  // Generate invoice number if not provided
  if (!invoiceData.invoiceNumber) {
    invoiceData.invoiceNumber = `INV-${Date.now()}`;
  }

  return await repo.create({
    ...invoiceData,
    lines: {
      create: lines.map(line => ({
        productId: line.productId,
        quantity: line.quantity,
        unit: line.unit,
        unitPrice: line.unitPrice,
        amount: line.amount,
        isAutoGenerated: line.isAutoGenerated
      }))
    }
  });
};

exports.getInvoices = async () => {
  return await repo.findMany({});
};

exports.getInvoiceById = async (id) => {
  const invoice = await repo.findById(id);
  if (!invoice) throw new ApiError(404, 'Invoice not found');

  const productIds = invoice.lines.map(line => line.productId).filter(Boolean);
  if (productIds.length > 0) {
    const products = await prisma.product.findMany({
      where: { id: { in: productIds } }
    });
    const productMap = new Map(products.map(p => [p.id, p]));
    invoice.lines = invoice.lines.map(line => ({
      ...line,
      product: productMap.get(line.productId) || null
    }));
  }

  return invoice;
};

exports.postInvoice = async (id) => {
  const invoice = await repo.findById(id);
  if (!invoice) throw new ApiError(404, 'Invoice not found');
  
  if (invoice.state === 'POSTED') {
    throw new ApiError(400, 'Invoice is already posted');
  }

  return await repo.updateState(id, 'POSTED', new Date());
};
