const { prisma } = require("../config/db");
const ApiError = require("../utils/apiError");

const calculateLateFee = async (orderId, inputActualReturnDate = null) => {
  return await prisma.$transaction(async (tx) => {
    // 1. Fetch Order including items, products, invoice, and vendor settings
    const order = await tx.order.findUnique({
      where: { id: orderId },
      include: {
        items: {
          include: {
            product: true,
          },
        },
        invoice: true,
      },
    });

    if (!order) {
      throw new ApiError(404, "Order not found");
    }

    const vendorSettings = await tx.vendorSettings.findUnique({
      where: { vendorId: order.vendorId },
    });

    if (!vendorSettings) {
      throw new ApiError(400, "Vendor settings not found");
    }

    const actualReturnDate = inputActualReturnDate ? new Date(inputActualReturnDate) : new Date();

    // 2. Compute late duration
    const scheduled = new Date(order.scheduledReturnDate);
    const diffMs = actualReturnDate.getTime() - scheduled.getTime();
    const diffMinutes = Math.max(0, Math.floor(diffMs / (60 * 1000)));
    const gracePeriod = Number(vendorSettings.lateFeeGracePeriodMinutes || 0);
    const lateMinutes = Math.max(0, diffMinutes - gracePeriod);
    const lateHours = Math.ceil(lateMinutes / 60);

    let lateFeeAmount = 0;
    let rate = 0;

    if (lateHours > 0) {
      // 3. Resolve rate: product override else defaultLateFeeRatePerHour
      const rentableItems = order.items.filter(item => !item.isAutoGenerated);
      const rates = rentableItems.map(item => {
        return item.product.lateFeeRatePerHour !== null
          ? Number(item.product.lateFeeRatePerHour)
          : Number(vendorSettings.defaultLateFeeRatePerHour || 0);
      });

      rate = rates.length > 0 ? Math.max(...rates) : Number(vendorSettings.defaultLateFeeRatePerHour || 0);

      // 4. Calculate amount with cap
      const maxCap = vendorSettings.maxLateFeeCap ? Number(vendorSettings.maxLateFeeCap) : Infinity;
      lateFeeAmount = Math.min(lateHours * rate, maxCap);

      const defaultLateFeeProductId = vendorSettings.defaultLateFeeProductId;
      if (!defaultLateFeeProductId) {
        throw new ApiError(400, "Default Late Fee Product ID is not configured in Vendor Settings");
      }

      // 5. Append or update OrderItem
      const existingOrderItem = order.items.find(
        item => item.productId === defaultLateFeeProductId && item.isAutoGenerated
      );

      if (existingOrderItem) {
        await tx.orderItem.update({
          where: { id: existingOrderItem.id },
          data: {
            quantity: lateHours,
            unitPrice: rate,
            amount: lateFeeAmount,
          },
        });
      } else {
        await tx.orderItem.create({
          data: {
            orderId: order.id,
            productId: defaultLateFeeProductId,
            quantity: lateHours,
            unitPrice: rate,
            amount: lateFeeAmount,
            isAutoGenerated: true,
          },
        });
      }

      // 6. Append or update InvoiceLine if mirrored invoice exists
      if (order.invoice) {
        const existingInvoiceLines = await tx.invoiceLine.findMany({
          where: { invoiceId: order.invoice.id },
        });
        const existingInvoiceLine = existingInvoiceLines.find(
          line => line.productId === defaultLateFeeProductId && line.isAutoGenerated
        );

        if (existingInvoiceLine) {
          await tx.invoiceLine.update({
            where: { id: existingInvoiceLine.id },
            data: {
              quantity: lateHours,
              unitPrice: rate,
              amount: lateFeeAmount,
            },
          });
        } else {
          await tx.invoiceLine.create({
            data: {
              invoiceId: order.invoice.id,
              productId: defaultLateFeeProductId,
              quantity: lateHours,
              unitPrice: rate,
              amount: lateFeeAmount,
              isAutoGenerated: true,
            },
          });
        }
      }
    }

    // 7. Update order actualReturnDate
    await tx.order.update({
      where: { id: order.id },
      data: {
        actualReturnDate,
      },
    });

    return {
      lateHours,
      lateFeeAmount,
    };
  });
};

module.exports = {
  calculateLateFee,
};
