const { z } = require('zod');

const invoiceLineSchema = z.object({
  productId: z.string().uuid(),
  quantity: z.number().min(0.01).default(1),
  unit: z.string().optional(),
  unitPrice: z.number().min(0),
  amount: z.number().min(0),
  isAutoGenerated: z.boolean().default(false)
});

const invoiceSchema = z.object({
  orderId: z.string().uuid(),
  invoiceNumber: z.string().optional(), // If not provided, we generate one
  untaxedAmount: z.number().min(0),
  taxPercent: z.number().min(0).max(100).default(0),
  taxAmount: z.number().min(0).default(0),
  totalAmount: z.number().min(0),
  lines: z.array(invoiceLineSchema).min(1),
});

const depositRefundSchema = z.object({
  penaltyAmountDeducted: z.number().min(0).default(0),
  razorpayRefundId: z.string().optional()
});

module.exports = { invoiceSchema, depositRefundSchema };
